name: platform
group:
  - operations_center
  - operator_console
  - repograph
  - protocolwarden.github.io
  - protocolwarden
  - switchboard
  - platformdeployment
  - custodian
  - cxrp
  - corerunner
  - sourceregistry
  - rxp
  - platformmanifest
  - teamexecutor
  - dagexecutor
  - critiqueexecutor
