[program:vpn-script]
command=/bin/bash /home/dev/Documents/personal-utils/manage-vpn.sh
directory=/home/dev/Documents/personal-utils
autostart=true
autorestart=true
stderr_logfile=/var/log/vpn-script.err.log
stdout_logfile=/var/log/vpn-script.out.log
startretries=3
startsecs=5
user=dev
